name: GitHub Encrypted Secrets
on: [push]
jobs:
  GitHub-Secrets:
    runs-on: ubuntu-latest
    steps:
        - uses: actions/checkout@v2
        - name: Use secret token
          env:
              TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
          run: |
            nbdev_test_nbs